<a href="https://colab.research.google.com/github/Hikaru-yokoo/EU_M_Math-Repositry/blob/main/chap2_Ex04%2605.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#行列式を求めよ2-4
import numpy as np
import scipy.linalg as linalg
matrix = np.array([[1,2,3],[1,3,2],[3,1,2]])
print(linalg.det(matrix))

#2-5逆行列、固有値と固有ベクトルを求める。
print("逆行列",linalg.inv(matrix))
eig_value,eig_vector = linalg.eig(matrix)
print("固有値",eig_value)
print("固有ベクトル",eig_vector)



-12.0
逆行列 [[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
固有値 [ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
固有ベクトル [[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]
